language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0

before_script:
  - composer selfupdate

install:
  - composer install

script:
  - bin/app tests:coverage clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover bin/clover.xml