version: '2'

services:
  php72:
    build: ./72
    volumes:
      - ../../:/app/monitoring
    working_dir: /app/monitoring
    command: [bash, -c, "composer install && make test"]
  php74:
    build: ./74
    volumes:
      - ../../:/app/monitoring
    working_dir: /app/monitoring
    command: [bash, -c, "composer install && make test"]